version: "3.9"

services:
  # Wav2Lip FastAPI Application  
  wav2lip-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: illuminus-wav2lip:latest
    container_name: illuminus_wav2lip
    restart: unless-stopped
    ports:
      - "9000:8000"  # External port 9000 to avoid conflicts
    volumes:
      - ./static:/app/static
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./models:/app/models
      - ./frontend:/app/frontend
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
      - NODE_ENV=production
    networks:
      - illuminus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  # Nginx Reverse Proxy 
  nginx:
    image: nginx:alpine
    container_name: illuminus_nginx
    restart: unless-stopped
    ports:
      - "9080:80"   # External port 9080 to avoid conflicts with other nginx
      - "9443:443"  # External port 9443 for future HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - ./static:/var/www/static
    networks:
      - illuminus-network
    depends_on:
      - wav2lip-app
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  illuminus-network:
    driver: bridge