version: "3.9"

services:
  illuminus:
    image: illuminus:latest
    build: .
    container_name: illuminus
    ipc: host
    ports:
      - "8000:8000"
    volumes:
      - ./:/workspace
    environment:
      - PYTHONPATH=/workspace
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload